### ISSUE TITLE
"Enter" key in search dialog should search instead of adding newline

### ISSUE THREAD

**Issue by bvibber** [JulienDev/BugDroid#1]
Looks like a great start!

I find that the on-screen keyboard in the "Words" field on the search dialog shows an enter/carriage return button which adds a newline; probably better if that can be swapped out for a submit/go button to trigger search. I'll poke at source later if you don't beat me to it. :)

**Comment by bvibber** [comment]
Pull request! https://github.com/JulienDev/BugDroid/pull/2

Also removes the bin/ and gen/ directories from the repo, so they can be rebuilt cleanly, and adds a .gitignore for em.

**Comment by JulienDev** [comment]
Thank you very much Brion for this patch ;) I merged it
