### ISSUE TITLE
Edit features

### ISSUE THREAD

**Issue by albfan** [JulienDev/BugDroid#10]
I have added such features in https://github.com/albfan/BoogDroid but would be great to add here on official android app.

Is that possible? I can send a PR.

**Comment by justdave** [comment]
You can try...  from the network graph it looks like you didn't fork from here though so I'm not sure if it'll work.

**Comment by justdave** [comment]
Or if you mean contributing new patches with the same features....  I'm not sure how official this app is, but it's great to have any apps that work. :-)

**Comment by albfan** [comment]
Yes I mean collaborate on project. I will provide PR then when I have time
