### ISSUE TITLE
Immediate NullPointerException at launch

### ISSUE THREAD

**Issue by bdube** [JulienDev/BugDroid#4]
When launching on ASUS TF101, Android 4.0.3, I get this error:

E/AndroidRuntime( 1762): FATAL EXCEPTION: main
E/AndroidRuntime( 1762): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.julienvermet.bugdroid/fr.julienvermet.bugdroid.menu.MenuActivity}: java.lang.NullPointerException
E/AndroidRuntime( 1762):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
E/AndroidRuntime( 1762):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
E/AndroidRuntime( 1762):        at android.app.ActivityThread.access$600(ActivityThread.java:123)
E/AndroidRuntime( 1762):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
E/AndroidRuntime( 1762):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1762):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1762):        at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 1762):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1762):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1762):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 1762):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 1762):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1762): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1762):        at fr.julienvermet.bugdroid.menu.MenuActivity.portrait(MenuActivity.java:127)
E/AndroidRuntime( 1762):        at fr.julienvermet.bugdroid.menu.MenuActivity.onCreate(MenuActivity.java:61)
E/AndroidRuntime( 1762):        at android.app.Activity.performCreate(Activity.java:4465)
E/AndroidRuntime( 1762):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
E/AndroidRuntime( 1762):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
E/AndroidRuntime( 1762):        ... 11 more
W/ActivityManager(  170):   Force finishing activity fr.julienvermet.bugdroid/.menu.MenuActivity

**Comment by bdube** [comment]
I don't reproduce the error on the emulator on ICS when compiling from master (commit ca676371a36). Is that newer than what's available in the market now?

**Comment by JulienDev** [comment]
I also received errors on the PlayStore and also on a Blackberry Playbook. This is strange.
Animations will be removed in the next version of BugDroid I'm designing :)

**Comment by bdube** [comment]
In my case, it seems that most of the calls to findViewById() in MenuActivity are returning null. I'm trying to find out why. My debugging output:

D/MenuActivity( 1568): ivInfo is android.widget.ImageView@41099178
D/MenuActivity( 1568): llMenu is null
D/MenuActivity( 1568): viewFlipper is null
D/MenuActivity( 1568): ivBugdroid is null

**Comment by justdave** [comment]
If it helps any, I can reproduce this on my CM9 tablet, but not on my ICS HTC phone, both running the same version of BugDroid from the market.  On the tablet it works fine if launched as a URL handler, but attempting to launch it via the shortcut icon in the home screen or the applications drawer results in the crash.  Works fine either way on the phone.  The tablet claims to be 4.0.4, the phone 4.0.3.
