### ISSUE TITLE
Support multiple Bugzilla accounts

### ISSUE THREAD

**Issue by justdave** [JulienDev/BugDroid#5]
I have two Bugzilla accounts on b.m.o.  I'm employed by Mozilla as a sysadmin, and I also run the Bugzilla project itself, so I use one for work-related stuff and the other for Bugzilla-related stuff.  It'd be useful to be able to switch between them at will.

I'm volunteering to implement this (already made a fork in github), filing the issue here to get it on the record.  I'll post a pull request when it's ready.

**Comment by JulienDev** [comment]
This is also planned for the v2 but as everything will be different I think this is not necessary to create a patch for that now. This is just my mind, if you want to implement the multi-account I'll update the app on the Play Store :)

**Comment by justdave** [comment]
I don't want to duplicate any effort if you're already working on it, but since it sounded like you were pretty busy these days I thought I'd offer to help.
